import Link from 'next/link';
import { notFound } from 'next/navigation';
import { AdminShell } from '@/components/admin/AdminShell';
import { Panel, SectionHeader, StatusBadge } from '@/components/admin/admin-ui';
import { requireAdmin } from '@/server/admin/require-admin';
import { listNetworkSites } from '@/server/admin/sites';
import { BriefActions } from './BriefActions';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

interface Params { params: Promise<{ id: string }> }

export default async function BriefDetail({ params }: Params) {
  const { admin, sb } = await requireAdmin('/admin/content/briefs');
  const sites = await listNetworkSites(sb);
  const { id } = await params;
  const { data: row } = await sb
    .from('network_content_briefs')
    .select('id, idea_id, site_id, content_type, payload, status, actor_type, ai_model, ai_est_cost_usd, ai_input_tokens, ai_output_tokens, generated_at, approved_at, rejection_reason, network_sites(slug, name), network_content_ideas(working_title, origin_type, evidence)')
    .eq('id', id).maybeSingle();
  if (!row) notFound();
  const b = row as unknown as {
    id: string; idea_id: string; site_id: string; content_type: string;
    payload: Record<string, unknown> & { suggested_h1?: string; purpose?: string; reader_intent?: string; primary_query?: string; secondary_queries?: string[]; evidence_summary?: string; recommended_angle?: string; outline?: Array<{ h2: string; h3s?: string[]; notes?: string }>; required_facts?: string[]; entities_to_mention?: string[]; suggested_internal_links?: Array<{ target_url: string; anchor: string; reason: string }>; external_source_requirements?: string[]; seo_notes?: string; suggested_meta_title?: string; suggested_meta_description?: string; suggested_schema_type?: string; things_not_to_claim?: string[]; freshness_requirements?: string; research_gaps?: string[] };
    status: string; actor_type: string; ai_model: string | null;
    ai_est_cost_usd: number | null; ai_input_tokens: number | null; ai_output_tokens: number | null;
    generated_at: string; approved_at: string | null; rejection_reason: string | null;
    network_sites: { slug: string; name: string };
    network_content_ideas: { working_title: string; origin_type: string; evidence: Record<string, unknown> };
  };
  const p = b.payload;

  return (
    <AdminShell admin={admin} sites={sites} activeSlug={b.network_sites.slug} pathname={`/admin/content/briefs/${id}`}>
      <SectionHeader
        eyebrow={`Content · Brief · ${b.network_sites.name}`}
        title={p.suggested_h1 ?? b.network_content_ideas.working_title}
        description={`${b.content_type.replace(/_/g, ' ')} · ${b.actor_type === 'ai' ? `generated by ${b.ai_model ?? 'AI'}` : 'human-authored'} · origin: ${b.network_content_ideas.origin_type}`}
        actions={<BriefActions briefId={b.id} status={b.status} />}
      />

      <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
        <StatusBadge state={b.status === 'approved' ? 'approved' : b.status === 'rejected' ? 'rejected' : 'pending'} label={b.status.replace(/_/g, ' ')} />
        {b.ai_est_cost_usd && <span className="col-dim" style={{ fontSize: 11 }}>{b.ai_input_tokens} in / {b.ai_output_tokens} out · ~${Number(b.ai_est_cost_usd).toFixed(4)}</span>}
        {b.rejection_reason && <span style={{ color: '#8A1C27', fontSize: 11 }}>reject: {b.rejection_reason}</span>}
      </div>

      <Panel title="Purpose & intent" eyebrow="Brief">
        <dl style={{ display: 'grid', gridTemplateColumns: '160px 1fr', gap: 10, fontSize: 13, margin: 0 }}>
          <dt className="col-dim">Purpose</dt><dd style={{ margin: 0 }}>{p.purpose ?? '—'}</dd>
          <dt className="col-dim">Reader intent</dt><dd style={{ margin: 0 }}>{p.reader_intent ?? '—'}</dd>
          <dt className="col-dim">Primary query</dt><dd style={{ margin: 0 }}><code>{p.primary_query ?? '—'}</code></dd>
          <dt className="col-dim">Secondary queries</dt><dd style={{ margin: 0 }}>{(p.secondary_queries ?? []).map((q) => <code key={q} style={{ marginRight: 8 }}>{q}</code>)}</dd>
          <dt className="col-dim">Recommended angle</dt><dd style={{ margin: 0 }}>{p.recommended_angle ?? '—'}</dd>
          <dt className="col-dim">Evidence summary</dt><dd style={{ margin: 0 }}>{p.evidence_summary ?? '—'}</dd>
          <dt className="col-dim">Freshness</dt><dd style={{ margin: 0 }}>{p.freshness_requirements ?? '—'}</dd>
        </dl>
      </Panel>

      <Panel title="Outline" eyebrow="Structure">
        {(p.outline ?? []).length === 0 ? <span className="col-dim">No outline.</span> : (
          <ol style={{ margin: 0, paddingLeft: 20 }}>
            {(p.outline ?? []).map((s, i) => (
              <li key={i} style={{ marginBottom: 10 }}>
                <strong>{s.h2}</strong>
                {s.notes && <div className="col-dim" style={{ fontSize: 12 }}>{s.notes}</div>}
                {(s.h3s ?? []).length > 0 && (
                  <ul style={{ marginTop: 4 }}>{(s.h3s ?? []).map((h, j) => <li key={j} style={{ fontSize: 12 }}>{h}</li>)}</ul>
                )}
              </li>
            ))}
          </ol>
        )}
      </Panel>

      <Panel title="Required facts & entities" eyebrow="Grounding">
        <h4 style={{ fontSize: 12, textTransform: 'uppercase', letterSpacing: '0.08em', margin: '0 0 4px' }}>Required facts</h4>
        <ul style={{ marginTop: 0 }}>{(p.required_facts ?? []).map((f, i) => <li key={i} style={{ fontSize: 13 }}>{f}</li>)}</ul>
        <h4 style={{ fontSize: 12, textTransform: 'uppercase', letterSpacing: '0.08em', margin: '12px 0 4px' }}>Entities to mention</h4>
        <ul style={{ marginTop: 0 }}>{(p.entities_to_mention ?? []).map((e, i) => <li key={i} style={{ fontSize: 13 }}>{e}</li>)}</ul>
      </Panel>

      <Panel title="Internal link suggestions" eyebrow="Routing">
        {(p.suggested_internal_links ?? []).length === 0 ? <span className="col-dim">No suggestions.</span> : (
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            {(p.suggested_internal_links ?? []).map((l, i) => (
              <li key={i} style={{ fontSize: 13, marginBottom: 6 }}>
                <strong>{l.anchor}</strong> → <a href={l.target_url} target="_blank" rel="noopener noreferrer">{l.target_url}</a>
                <div className="col-dim" style={{ fontSize: 11 }}>{l.reason}</div>
              </li>
            ))}
          </ul>
        )}
      </Panel>

      <Panel title="Meta + SEO" eyebrow="Delivery">
        <dl style={{ display: 'grid', gridTemplateColumns: '160px 1fr', gap: 10, fontSize: 13, margin: 0 }}>
          <dt className="col-dim">Meta title</dt><dd style={{ margin: 0 }}>{p.suggested_meta_title ?? '—'}</dd>
          <dt className="col-dim">Meta description</dt><dd style={{ margin: 0 }}>{p.suggested_meta_description ?? '—'}</dd>
          <dt className="col-dim">Schema type</dt><dd style={{ margin: 0 }}>{p.suggested_schema_type ?? '—'}</dd>
          <dt className="col-dim">SEO notes</dt><dd style={{ margin: 0 }}>{p.seo_notes ?? '—'}</dd>
        </dl>
      </Panel>

      {(p.things_not_to_claim ?? []).length > 0 && (
        <Panel title="Things NOT to claim" eyebrow="Guardrails">
          <ul style={{ marginTop: 0 }}>{(p.things_not_to_claim ?? []).map((f, i) => <li key={i} style={{ fontSize: 13 }}>{f}</li>)}</ul>
        </Panel>
      )}
      {(p.research_gaps ?? []).length > 0 && (
        <Panel title="Research required" eyebrow="Unresolved">
          <ul style={{ marginTop: 0 }}>{(p.research_gaps ?? []).map((f, i) => <li key={i} style={{ fontSize: 13, color: '#8A6A1C' }}>{f}</li>)}</ul>
        </Panel>
      )}
      {(p.external_source_requirements ?? []).length > 0 && (
        <Panel title="External sources required" eyebrow="Sourcing">
          <ul style={{ marginTop: 0 }}>{(p.external_source_requirements ?? []).map((f, i) => <li key={i} style={{ fontSize: 13 }}>{f}</li>)}</ul>
        </Panel>
      )}

      <div><Link className="status-badge status-not_connected" href="/admin/content/briefs">← All briefs</Link></div>
    </AdminShell>
  );
}
