import { NextResponse } from 'next/server';

// Sitemap index. References every shard generated by src/app/sitemap.ts's
// generateSitemaps(). Exposed at /sitemap-index.xml to avoid colliding
// with Next's metadata `sitemap.ts` mechanic which owns /sitemap.xml.
// robots.txt points crawlers here.

export const dynamic = 'force-static';
export const revalidate = 86_400;

const SHARDS = ['base', 'cards', 'printings-0', 'printings-1'] as const;

export function GET() {
  const siteUrl =
    process.env['NEXT_PUBLIC_SITE_URL'] ?? 'https://duelistprices.example';
  const now = new Date().toISOString();
  const body =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    SHARDS.map(
      (id) =>
        `  <sitemap>\n    <loc>${siteUrl}/sitemap/${id}.xml</loc>\n    <lastmod>${now}</lastmod>\n  </sitemap>`,
    ).join('\n') +
    `\n</sitemapindex>\n`;
  return new NextResponse(body, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600, s-maxage=86400',
    },
  });
}
